### PR TITLE
add ESP-IDF v5 support

### PR DESCRIPTION
**Pull request by phatpaul**
Just some minor fixes to make it build in ESP-IDF v5.
But I think the future of this library should use the TWAI API like this one: https://github.com/sergei/NMEA2000_esp32_twai
That should allow it to support more ESP32-xx chips.

### CODE REVIEW

**Comment by ttlappalainen** [comment]
Always do only strictly necessary changes. Do no do unnecessary formatting and specially formatting changes which changes readability like below:
```
tNMEA2000_esp32::tNMEA2000_esp32(gpio_num_t _TxPin,  gpio_num_t _RxPin) :
    tNMEA2000(), IsOpen(false),
                                                                         speed(CAN_SPEED_250KBPS), TxPin(_TxPin), RxPin(_RxPin),
    RxQueue(NULL), TxQueue(NULL) {
}

```

After you changes library does not compile wit older versions.

Before you do pull, test that new version compiles with Arduino and platform io olde versions too.

**Comment by phatpaul** [comment]
Sorry I didn't notice that formatting change.  I'll undo the formatting and just keep the necessary changes.

Do you have a list of Arduino and PlatformIO versions that this library should support?  That's quite a burden to ask for testing each PR with multiple environments. A CI would be nice to do this automatically.

**Comment by phatpaul** [comment]
I fixed the formatting.  Can you please reopen this PR?  Or should I create a new one?

I added a table of support: https://github.com/phatpaul/NMEA2000_esp32/blob/master/README.adoc#compatibility
I could also look into setting up a CI action that builds all of those and reports the build status pass/fail.

**Comment by ttlappalainen** [comment]
Still does not compile. Must be tested at lease with PlatformIO Espressif 3.5 and Arduino 1.8/2.

New PR. Github is stupid in that point. If you update same PR 10 time back and forth, then you have 10 updates on final merge, which then makes it difficult on final to see where all started and compare true changes. Maybe there is some better way for this. I do tests always first locally before pulling anything.

Remove other changes and add:
```
...
#if !defined(round)
  #include <math.h>
#endif

#ifndef PERIPH_CAN_MODULE
  #define PERIPH_CAN_MODULE PERIPH_TWAI_MODULE
  #define DPORT_CAN_CLK_EN DPORT_TWAI_CLK_EN
  #define DPORT_CAN_RST DPORT_TWAI_RST
  #define CAN_RX_IDX TWAI_RX_IDX
  #define CAN_TX_IDX TWAI_TX_IDX
#endif

```

Currently there is no support for S2 and S3 chips. 

Note that current library passes NMEA2000 certification when compiled on arduino espressif. To make full tests again for TWAI API is a job and do not when that would happen.

**Comment by ttlappalainen** [comment]
Note you can have indents within #if...#endif to improve reading.
```
#include "esp_idf_version.h"
#if ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(5, 0, 0)
  // enable support for ESP-IDF v5.0+
  #include "esp_private/periph_ctrl.h"
#else
  #include "driver/periph_ctrl.h"
#endif

#include "rom/gpio.h"
#include "soc/gpio_sig_map.h"
#include "soc/dport_reg.h"
#include "soc/dport_access.h"
#include "NMEA2000_esp32.h"

#if !defined(round)
  #include <math.h>
#endif

#ifndef PERIPH_CAN_MODULE
  #define PERIPH_CAN_MODULE PERIPH_TWAI_MODULE
  #define DPORT_CAN_CLK_EN DPORT_TWAI_CLK_EN
  #define DPORT_CAN_RST DPORT_TWAI_RST
  #define CAN_RX_IDX TWAI_RX_IDX
  #define CAN_TX_IDX TWAI_TX_IDX
#endif
```

Update also Copyright to 2015-2023 on .cpp, .h and .adoc

**Comment by phatpaul** [comment]
On other projects that I have contributed to, the PR stays open and I just rebase and squash all commits then force push.  That updates the PR and keeps the final changes to 1 commit, and we can use the PR thread to discuss changes.  There's no need to close the PR unless you are sure you don't want any of this.

**Comment by ttlappalainen** [comment]
I have wondered problem to others too and you are the first saying that there is way to avoid it.

Not it anyway says that "The master branch is force-pushed or recreated" and does not allow to reopen.

**Comment by phatpaul** [comment]
Just a note, I found these other implementations:
https://github.com/sergei/NMEA2000_esp32_twai
https://github.com/ktand/NMEA2000_esp32_twai
https://github.com/jiauka/NMEA2000_esp32xx

**Pull request closed without merging**
