### PR TITLE
Add support for use as an ESP-IDF component

### PR DESCRIPTION
**Pull request by nicklasb**
* Add CMakeLists.txt
* Add idf_component.yml
* Include math if round isn't defined
* Add note in version log and update copyright

### CODE REVIEW

**Comment by nicklasb** [comment]
Ok, so now this is as it should be I think. 
Now NMEA2000_ESP32 works as an ESP-IDF-component.

I saw, however, that the CMakeLists.txt in the NMEA2000 library still uses the top level project(NMEA2000) style in its CMakeList.txt, also I am not sure that config style works with newer versions of ESP-IDF.

To NMEA2000 work as a component (which seems the natural way to use it in ESP-IDF) I just added the minimal:
```
FILE(GLOB_RECURSE sources ./src/*.*)
idf_component_register(SRCS ${sources} 
INCLUDE_DIRS "." "src"
)
```

Obviously that doesn't include catch.hpp and the rest, not that knowledgeable of that stuff, but I presume you'd like to add that.

**Comment by phatpaul** [comment]
Hi @nicklasb could you provide a bit more detail on how to implement this library as a component in ESP-IDF?
A few steps to follow or a sample project would be very helpful.

**Comment by nicklasb** [comment]
Hi! @phatpaul,
I am not completely sure what you are asking for, this PR is such an implementation?
To use it as such, add it to your `components` library and add a `REQUIRES` to it in the CMaketext.txt of your project.

**Comment by nicklasb** [comment]
Ah, ok, this PR was only for this repo, I don't know how the other one does it. 
WRT loop, you don't need that on ESP-IDF, just move that to a cpp file where you can call it. Or write the ESP-IDF in C++, just call it .cpp .

**Comment by ttlappalainen** [comment]
Some notes:
- For binary control device use class 30 and function 140 for SetDeviceInformation. It is informative for other devices what you do.
- In TaskN2kBinStatus you can use synchronization timer you have initialized:
```
    if ( (statusNeedsUpdate) || (binStatusScheduler.IsTime()))
    {
        binStatusScheduler.UpdateNextTime();
```

- To call loop, you can create an other task. Or if you call it in your main, take care you use max. 1 ms delay on loop. You have to handle other calls with scheduler types like tN2kSyncScheduler or tN2kScheduler. If you use own task, take care of data locking.
- You must also create ISO Request handler and configure it with NMEA2000.SetISORqstHandler(..); in initialization. If there is request for 127501, you must respond to it. Something like this:
NMEA2000.SetISORqstHandler(ISORequestHandler);
...
bool ISORequestHandler(unsigned long RequestedPGN, unsigned char Requester, int DeviceIndex) {
  if ( RequestedPGN==127501UL ) {
    SendN2kBinaryStatus();
    return true;
  }

  return false;
}
- You should also handle group function messages 126208. I have written handler functions and published them on some issue under NMEA2000

**Comment by phatpaul** [comment]
Thanks for the tips.
I created a repository for this example project: https://github.com/phatpaul/NMEA2000_switchbank_example_esp-idf

@ttlappalainen  I'm having trouble integrating your class N2kGroupFunctionBinaryStatus which I found here: https://github.com/ttlappalainen/NMEA2000/issues/162#issuecomment-595265301
Maybe that was written for an older version of the library and needs some refactoring?
How do I call the constructor?
https://github.com/phatpaul/NMEA2000_switchbank_example_esp-idf/blob/392a76cb67f22f35cd905cc1b284447a77d87e49/components/my_N2K_lib/my_N2K_lib.cpp#L154

And there is a compile error here:
https://github.com/phatpaul/NMEA2000_switchbank_example_esp-idf/blob/392a76cb67f22f35cd905cc1b284447a77d87e49/components/my_N2K_lib/N2kGroupFunctionBinaryStatus.cpp#L51

Also, could you elaborate on what you mean by take care of data locking?  And I know FreeRTOS tasks typically run at 10ms interval.  Is that too slow?

> To call loop, you can create an other task. Or if you call it in your main, take care you use max. 1 ms delay on loop. You have to handle other calls with scheduler types like tN2kSyncScheduler or tN2kScheduler. If you use own task, take care of data locking.

**Comment by ttlappalainen** [comment]
Here is newer version, compiles on project I updated lately. It is also on some other issue.
[N2kGroupFunctionBinaryStatus.zip](https://github.com/ttlappalainen/NMEA2000_esp32/files/11539994/N2kGroupFunctionBinaryStatus.zip)

10 ms is rather max., it it is continuous. Anyway 10 ms switching is other than loop speed on task. If you have several tasks, system gives 10 ms slice for each. But when other task uses less than that e.g., by yield/sleep/delay, it moves to next. Also if you have 10 equal priority tasks, which all needs full 10 ms, you will have totally 100 ms delay before your task will be called again. In point of N2k communication this is nearly catastrofic. The solution for this is to rise task priority. Then if you have 10 tasks with same priority and 1 with higher priority, the higher priority task will be called after each task change and max delay is 10 ms. I used 100 ns delay for N2k task, when I made test with RPi. It does not use much cpu, since it moslty checks is there anything to do and goes sleep again.

You need to create functions for handling and then provide them on constructor:
```
  pBinaryStatusGroupFunctionHandler=
     new tN2kGroupFunctionHandlerForPGN127501(&NMEA2000,
               &HasInstance,
               &SetBinaryStatusMessage,
               &ChangeInstance,
               &ChangeTransmissionInterval);
  NMEA2000.AddGroupFunctionHandler(pBinaryStatusGroupFunctionHandler);

```
I can not give samples for callbacks, since they depend very much of how you code has been written.

Data locking is normal thing to take care in multitasking systems. If you are running several tasks, which may use same data, there is risk of corruption. If you e.g., read data from bus on one task to global variables and display them on other, you may see time to time strangle values. This is not so critical, but if you e.g., generate alarms according values, you may get false alarms.  Please study more about data locking, mutex and semaphore.

**Comment by phatpaul** [comment]
Thanks for the updated code.
I'm familiar with data locking in general. I thought you were referring to something specifically that I need to protect in this library when using it.

What is the meaning of "Instance" in the context of tN2kGroupFunctionHandlerForPGN127501?

Is it for allowing another device to change the NMEA2000 Device Instance of my device? I figure my device will only have 1 instance (2 banks of switches).  But there could be multiple instances of my device on the bus.  

Or is that referring to a Data Instance representing one switch?  Or is that an instance of a Bank of 28 switches?

**Comment by phatpaul** [comment]
I'm getting task watchdog timeouts constantly as I implemented the task as simply 
```    
for (;;)
    {
        // put your main code here, to run repeatedly:
        TaskN2kBinStatus();
        NMEA2000.ParseMessages();
    }
```
I guess I need a yield in there or ideally wait for an interrupt or event that a CAN message is received.  I'm going to try to look into how this project accomplished it using a queue: https://github.com/sergei/sci2000/blob/47209b7944ff5f0d65d0851fb919fc2489df41df/mhu2nmea/main/N2KHandler.cpp#L144

BTW he is also using an updated version of this library https://github.com/sergei/NMEA2000_esp32_twai which uses the APIs in ESP-IDF.  I think I will switch to that eventually b/c it should support IDF v5 and ESP32-S3.

**Comment by ttlappalainen** [comment]
You need to use sleep. 1 ms is ok. If possible 0.5. Note that you can not just wain interrupts. NMEA2000.ParseMessages(); does other things too, which are not related to received messages.

I know twai version, but have not had time to do tests does it work preopery in NMEA2000 but. Most CAN drivers I have used has not worked properly with NMEA2000 - this is why I have to maintain own versions.

**Pull request merged**
